-- Create Epic Clarity schema tables
-- This script runs as the CLARITY user

-- Connect to the pluggable database and switch to CLARITY user
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = CLARITY;

-- Table 1: CLARITY_DEP (Departments)
-- Must be created first as it's referenced by PAT_ENC
CREATE TABLE CLARITY_DEP (
    DEPARTMENT_ID NUMBER(18) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(254),
    DEPARTMENT_ABBR VARCHAR2(50),
    REV_LOC_ID NUMBER(18),
    SPECIALTY VARCHAR2(254),
    CONSTRAINT PK_CLARITY_DEP PRIMARY KEY (DEPARTMENT_ID)
);

-- Table 2: PATIENT (Patient Demographics)
-- Core patient information
CREATE TABLE PATIENT (
    PAT_ID VARCHAR2(18) NOT NULL,
    PAT_MRN_ID VARCHAR2(50) NOT NULL,
    PAT_NAME VARCHAR2(254),
    PAT_FIRST_NAME VARCHAR2(100),
    PAT_LAST_NAME VARCHAR2(100),
    BIRTH_DATE DATE,
    SEX_C VARCHAR2(10),
    DEATH_DATE DATE,
    ADD_LINE_1 VARCHAR2(254),
    CITY VARCHAR2(100),
    STATE_C VARCHAR2(10),
    ZIP VARCHAR2(20),
    CONSTRAINT PK_PATIENT PRIMARY KEY (PAT_ID),
    CONSTRAINT UK_PATIENT_MRN UNIQUE (PAT_MRN_ID)
);

-- Table 3: PAT_ENC (Patient Encounters)
-- References PATIENT and CLARITY_DEP
CREATE TABLE PAT_ENC (
    PAT_ENC_CSN_ID NUMBER(18) NOT NULL,
    PAT_ID VARCHAR2(18) NOT NULL,
    CONTACT_DATE DATE,
    DEPARTMENT_ID NUMBER(18),
    ENC_TYPE_C VARCHAR2(10),
    APPT_STATUS_C VARCHAR2(10),
    APPT_TIME DATE,
    HOSP_ADMSN_TIME DATE,
    HOSP_DISCH_TIME DATE,
    CONSTRAINT PK_PAT_ENC PRIMARY KEY (PAT_ENC_CSN_ID),
    CONSTRAINT FK_PAT_ENC_PATIENT FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
    CONSTRAINT FK_PAT_ENC_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES CLARITY_DEP(DEPARTMENT_ID)
);

-- Table 4: ORDER_PROC (Procedure Orders)
-- References PAT_ENC
CREATE TABLE ORDER_PROC (
    ORDER_PROC_ID NUMBER(18) NOT NULL,
    PAT_ENC_CSN_ID NUMBER(18),
    PROC_ID NUMBER(18),
    PROC_CODE VARCHAR2(50),
    PROC_NAME VARCHAR2(254),
    ORDER_TIME DATE,
    ORDER_STATUS_C VARCHAR2(10),
    ORDERING_PROVIDER_ID VARCHAR2(18),
    RESULT_TIME DATE,
    RESULT_STATUS_C VARCHAR2(10),
    CONSTRAINT PK_ORDER_PROC PRIMARY KEY (ORDER_PROC_ID),
    CONSTRAINT FK_ORDER_PROC_ENC FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID)
);

-- Table 5: CLARITY_MEDICATION (Medication Master)
-- Standalone medication reference table
CREATE TABLE CLARITY_MEDICATION (
    MEDICATION_ID NUMBER(18) NOT NULL,
    NAME VARCHAR2(254),
    GENERIC_NAME VARCHAR2(254),
    PHARM_CLASS VARCHAR2(254),
    PHARM_SUBCLASS VARCHAR2(254),
    CONTROLLED_SUBST_C VARCHAR2(10),
    DOSE_UNIT_C VARCHAR2(10),
    CONSTRAINT PK_CLARITY_MEDICATION PRIMARY KEY (MEDICATION_ID)
);

-- Table 6: ORDER_MED (Medication Orders)
-- References PAT_ENC and CLARITY_MEDICATION
CREATE TABLE ORDER_MED (
    ORDER_MED_ID NUMBER(18) NOT NULL,
    PAT_ENC_CSN_ID NUMBER(18),
    MEDICATION_ID NUMBER(18),
    ORDER_TIME DATE,
    ORDER_STATUS_C VARCHAR2(10),
    ORDERING_PROVIDER_ID VARCHAR2(18),
    START_DATE DATE,
    END_DATE DATE,
    HV_DISCRETE_DOSE NUMBER(12,6),
    DOSE_UNIT_C VARCHAR2(10),
    FREQ_NAME VARCHAR2(254),
    CONSTRAINT PK_ORDER_MED PRIMARY KEY (ORDER_MED_ID),
    CONSTRAINT FK_ORDER_MED_ENC FOREIGN KEY (PAT_ENC_CSN_ID) REFERENCES PAT_ENC(PAT_ENC_CSN_ID),
    CONSTRAINT FK_ORDER_MED_MED FOREIGN KEY (MEDICATION_ID) REFERENCES CLARITY_MEDICATION(MEDICATION_ID)
);

-- Create indexes for common queries
CREATE INDEX IDX_PAT_ENC_PAT_ID ON PAT_ENC(PAT_ID);
CREATE INDEX IDX_PAT_ENC_DATE ON PAT_ENC(CONTACT_DATE);
CREATE INDEX IDX_ORDER_PROC_ENC ON ORDER_PROC(PAT_ENC_CSN_ID);
CREATE INDEX IDX_ORDER_MED_ENC ON ORDER_MED(PAT_ENC_CSN_ID);
CREATE INDEX IDX_PATIENT_MRN ON PATIENT(PAT_MRN_ID);

-- Display success message
SELECT 'Epic Clarity schema tables created successfully' AS STATUS FROM DUAL;
